module SimpleColumn
  module Scopes
    module Version
      VERSION: String
    end
    VERSION: String
  end

  class Scopes
    module Version
      VERSION: String
    end
    VERSION: String
  end
end
